name: 02 - Workflow Events
on: [workflow_dispatch]
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the triggering event
              run: 'echo "This workflow was triggered by: ${{ github.event_name }}"'